### ISSUE TITLE
http testing for gaia docker-compose 

### ISSUE THREAD

**Issue by GInxh** [blockstack/gaia#177] opened 2019-01-09 18:17 UTC
set up docker-compose files to support develop gaia branch for new api admin sidecar configuration.

**Comment by GInxh** [comment] 2019-01-14 23:56
Left to do for Admin sidecar API: 
Hub config 
* port configuration for hub needs to be supported by passing in the hub port as a variable in the docker-compose which can be reloaded upon the reload and tested as an isolated configuration change in addition to being changed with all the permutations of other variables. Besides mounting to local disk, which will be preconfigured in pushed images, it is the only one (outside of future features like size limitation changes) that will require changing the docker-compose configuration itself and not fully automated in the http settings. 

* reload needs to script docker stop hub admin &  a change that supports the first star for uploading a change in the docker-compose port variable. I think this cannot be done live and a docker-compose down and up will need to be made. I need to investigate this still. 

AWS Keys: 
* remote keys for cloud hosting api call to be tested when SSL is configured.
* will be tested locally before formal SSL instructions made

**Comment by GInxh** [comment] 2019-01-23 18:03
reload

whitelist: to test with pre-existing whitelist 

aws keys

port config (saved for later)

hub disk overwrite (sep dependent bug)

**Comment by wileyj** [comment] 2019-02-04 15:22
all tests are done and working as intended. 
1 caveat: users should not adjust the port using the docker-compose file - if they do, nginx configuration will need to also be manually edited and reloaded. this is less than ideal and should be discouraged until the admin sidecar can update nginx config as well.
side point: changing the hub url shouldn't be necessary since we're proxying from nginx.

**Comment by moxiegirl** [comment] 2019-02-12 04:24
@GInxh reopen if you think this closed in error.

**Closed by moxiegirl** 2019-02-12 04:24 UTC
Labels: feature
