### ISSUE TITLE
Blockstack core not working on localhost after installing gaia.

### ISSUE THREAD

**Issue by inzig** [blockstack/gaia#75] opened 2017-10-16 11:49 UTC
My Auth Login was working with simple Blockstack core installation.
But as soon as i install gaia with python install. I am unable to Login / storedata, it jsut get stuck on choose your data storage part. 
Guide ASAP i am working on production blockstack.
Bear in mind that the error in console is following.
i am working in localhost envirement.
TypeError: NetworkError when attempting to fetch resource

**Comment by inzig** [comment] 2017-10-17 11:52
@jcnelson  Need your help, as i am stuck this issue i am stuck with gaia i don't even know how to uninstall it so atleast i could use localstorage.
Currently unable to move forward from this link.

>http://localhost:8888/account/storage#gaiahub

please help me to resolve this issue i am looking to build a dapp over blockstack. using gaia storage dropbox.

**Comment by jackzampolin** [comment] 2017-10-17 13:45
This is a duplicate of https://github.com/blockstack/blockstack-core/issues/653. Closing in favor of that issue.

**Closed** 2017-10-18 07:11 UTC
